### ISSUE TITLE
Allow CommentSection import

### ISSUE THREAD

**Issue by marcofranssen** [czue/bluesky-comments#15]
Would be great if the published npm package allows for importing the CommentSection component directly like this.

```tsx
"use client";

import { CommentSection } from "bluesky-comments";

export default function BlueskyComments({ author = "marcofranssen.nl" }) {
  return <CommentSection author={author} />
}
```

I'm trying to integrate the component directly into my NextJS based page.

However at the moment the npm package only contains the compiled distribution that doesn't export the React Components.

Looking forward to your response, would love to contribute here instead of copying code over to my project.

**Comment by czue** [comment]
Do you have an example/test project where I can reproduce this by any chance? 

Would love to support this use case but might take me a little longer if I have to spin up my own project to test it

**Comment by marcofranssen** [comment]
I don't have a public one,

But just use the nextjs starter using npx.

Then add your component in a page like shown above in my comment and you will see the compiled version of your package doesn't expose the components.

**Comment by czue** [comment]
thanks. making some progress on this. will hopefully have something to test or out tomorrow

**Comment by czue** [comment]
@marcofranssen I believe I have this all working now. Can you try on the latest version with something like this and let me know if it works?

```javascript
import 'bluesky-comments/bluesky-comments.css'
import { CommentSection } from "bluesky-comments";

function App() {
  return (
    <>
      <div>Comments Will Display Below</div>
        <CommentSection
           author="coryzue.com"
           uri=""
           onEmpty={() => <div>No comments yet</div>}
           commentFilters={[]} />
      </div>
    </>
  )
}
```

**Comment by skoch** [comment]
+1 for this feature, thank you.

@czue Are you accepting PRs? I cannot get this operational as is due to a few issues (`@types/*`, `*d.ts`, etc) and would like to help if I can.

**Comment by czue** [comment]
Hey - yes very open to PRs, that would be great! Also feel free to add more specifics about what's not working for you in new issues.

**Comment by skoch** [comment]
@czue Cool, thanks! Busy week, I should have something today. 

Basically, I believe you can just use one configuration and get the best of both worlds. I'd add `/dev` in there that would house example usage as well as a place to "npm run dev" via the config to develop against.

I have other thoughts as well but one thing at a time... ;)

**Comment by marcofranssen** [comment]
```
"use client";

import { Suspense } from "react";
import 'bluesky-comments/bluesky-comments.css';
import { CommentSection } from "bluesky-comments"

export default function BlueskyComments() {
  return (
    <Suspense fallback={<div>Loading comments…</div>}>
      <CommentSection
        author="marcofranssen.nl"
        onEmpty={() => <div>No comments yet.</div>} />
    </Suspense>
  );
}
```

This results now in following runtime error.

```
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at http://localhost:3000/_next/static/chunks/59ae1_bluesky-comments_dist_bluesky-comments_es_f6fddb.js:236:20
    at Em (http://localhost:3000/_next/static/chunks/59ae1_bluesky-comments_dist_bluesky-comments_es_f6fddb.js:637:6)
    at [project]/node_modules/.pnpm/bluesky-comments@0.8.0_react-dom@19.0.0_react@19.0.0__react@19.0.0/node_modules/bluesky-comments/dist/bluesky-comments.es.js [app-client] (ecmascript) (http://localhost:3000/_next/static/chunks/59ae1_bluesky-comments_dist_bluesky-comments_es_f6fddb.js:640:65)
    at http://localhost:3000/_next/static/chunks/_5b219e._.js:693:27
    at runModuleExecutionHooks (http://localhost:3000/_next/static/chunks/_5b219e._.js:738:9)
    at instantiateModule (http://localhost:3000/_next/static/chunks/_5b219e._.js:691:9)
    at getOrInstantiateModuleFromParent (http://localhost:3000/_next/static/chunks/_5b219e._.js:624:12)
    at esmImport (http://localhost:3000/_next/static/chunks/_5b219e._.js:142:20)
    at [project]/src/components/bluesky-comments.tsx [app-client] (ecmascript) (http://localhost:3000/_next/static/chunks/src_d3e6c6._.js:359:320)
    at http://localhost:3000/_next/static/chunks/_5b219e._.js:693:27
    at runModuleExecutionHooks (http://localhost:3000/_next/static/chunks/_5b219e._.js:738:9)
    at instantiateModule (http://localhost:3000/_next/static/chunks/_5b219e._.js:691:9)
    at getOrInstantiateModuleFromParent (http://localhost:3000/_next/static/chunks/_5b219e._.js:624:12)
    at commonJsRequire (http://localhost:3000/_next/static/chunks/_5b219e._.js:157:20)
    at requireModule (http://localhost:3000/_next/static/chunks/2e4ec_next_dist_compiled_80c993._.js:2676:29)
    at initializeModuleChunk (http://localhost:3000/_next/static/chunks/2e4ec_next_dist_compiled_80c993._.js:3218:25)
    at resolveModuleChunk (http://localhost:3000/_next/static/chunks/2e4ec_next_dist_compiled_80c993._.js:3187:43)
    at http://localhost:3000/_next/static/chunks/2e4ec_next_dist_compiled_80c993._.js:3527:24
```

**Comment by czue** [comment]
Ok, let me see if I can reproduce. I was testing on a vite app so maybe there's something unique to next.js that's causing this.

**Comment by skoch** [comment]
@czue I have something (apologies for the delay) however am met with an error when attempting to push a new branch.

```
❯ git push -u origin skoch/react-component
ERROR: Permission to czue/bluesky-comments.git denied to skoch.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by czue** [comment]
@skoch I think you have to fork the repo and then submit a PR from your own fork. https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by skoch** [comment]
@czue Thought you'd prefer adding folks as collaborators. Will get to this later then!

**Comment by czue** [comment]
happy to add you after the first PR assuming all goes well :)
